const community = {
    getEvents: '/events',
    getPosts: '/posts',
    getUserPosts: '/posts/:userId',
    uploadPhoto: '/upload-photo',
    getSuggestUsers: '/getSuggestUsers',
    createPost: '/create-post',
    uploadEventPhoto: '/upload-event-photo',
    createEvent: '/create-event',
    savePost: '/save-post',
    unsavePost: '/unsave-post',
    likePost: '/like-post',
    unlikePost: '/unlike-post',
    attendEvent: '/attend-event',
    notAttendEvent: '/notattend-event',
    isAttendedEvent: '/isAttended-event',
    getComments: '/get-comments',
    addComment: '/add-comment',
    getFollows: '/get-follows/:userId',
    getCountPosts: '/get-count-posts/:userId',
    getUserInfo: '/get-userInfo/:userId',
    checkPostStatus: '/check-post-status',
    getRandomPosts: '/get-random-posts',
    checkEventStatus: '/check-event-status',
};

export { community };
